export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Testimonials } from './Testimonials'
export { default as FAQ } from './FAQ'
export { default as Footer } from './Footer'
